version: "2.3"
services:
  simple_app:
    image: simple_app:0.0
    container_name: simple_app
    env_file:
      - .env
    #environment:
    #no environment variable to define right now
    volumes:
      - ${LOCAL_DIR}:/workspace/save
    ports:
      - "5006:5006"
    privileged: true
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:172.10.0.1"
networks:
  default-network:
    driver: bridge
    #ipam:
    #  driver: default
      #config:
      #  - subnet: 172.10.0.1/16